version: "3.8"
services:
  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/user_management_service/app
    env_file:
      - .env
    environment:
      - API_ENVIRONMENT=local
    depends_on:
      - postgres
      - redis
    networks:
      app1_net:
        ipv4_address: 192.168.0.4

  postgres:
    image: postgres:14
    restart: always
    environment:
      DB_USER: postgres
      DB_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      app1_net:
        ipv4_address: 192.168.0.2
    # env_file:
    #   - .env

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      app1_net:
        ipv4_address: 192.168.0.3

volumes:
    postgres-data:
    redis-data:

networks:
  app1_net:
    ipam:
      driver: default 
      config:
      - subnet: "192.168.0.0/24"  #ipv4
        gateway: 192.168.0.1
