"""Removed deleted tables

Revision ID: 3f3f3f29feac
Revises: f5b9a118e50c
Create Date: 2023-08-04 13:25:39.124376

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3f3f3f29feac"
down_revision = "f5b9a118e50c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
