"""Update hashed-password constraints

Revision ID: 4da218ee57ca
Revises: 1fa1a103e8b1
Create Date: 2023-07-09 21:52:08.871335

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4da218ee57ca"
down_revision = "1fa1a103e8b1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_table", "hashed_password", existing_type=sa.VARCHAR(length=100)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_table", "hashed_password", existing_type=sa.VARCHAR(length=15)
    )
    # ### end Alembic commands ###
