"""add field constraints

Revision ID: 57ce77b48037
Revises: 3bafdd52f328
Create Date: 2023-07-09 20:10:57.925154

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "57ce77b48037"
down_revision = "3bafdd52f328"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user_table", ["email"])
    op.create_unique_constraint(None, "user_table", ["phone_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_table", type_="unique")
    op.drop_constraint(None, "user_table", type_="unique")
    # ### end Alembic commands ###
