"""Added image_path, selectin

Revision ID: c2fb37fce0ac
Revises: d67bcd3e68da
Create Date: 2023-07-02 15:40:14.355953

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c2fb37fce0ac"
down_revision = "d67bcd3e68da"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("image_path", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "image_path")
    # ### end Alembic commands ###
