"""Update hashed-password constraints

Revision ID: f5b9a118e50c
Revises: 4da218ee57ca
Create Date: 2023-07-09 21:57:30.017189

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f5b9a118e50c"
down_revision = "4da218ee57ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_table",
        "hashed_password",
        existing_type=sa.VARCHAR(length=15),
        type_=sa.VARCHAR(length=100),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_table",
        "hashed_password",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.VARCHAR(length=15),
    )
    # ### end Alembic commands ###
